### Testing REST APIs

### Get all

GET http://localhost:5000/basicUser

### Get by id

GET http://localhost:5000/basicUser/62654f2597fb64052d7af5de

### Create one

POST http://localhost:5000/basicUser
Content-Type: application/json

{
 "first_name":"test_name"
}

### Update one
PATCH http://localhost:5000/basicUser/62654f2597fb64052d7af5de
Content-Type: application/json

{
    "first_name":"New Name"
}

### Delete one
DELETE http://localhost:5000/basicUser/62654f2597fb64052d7af5de

### Get Specialty by name
GET http://localhost:5000/basicUser?first_name=Marwan&phone_number=71223456

### Get All doctors
GET http://localhost:5000/doctor

### Create doctor
POST http://localhost:5000/doctor
Content-Type: application/json

{
    "basic_user_id": "6269063b6fb7b43092238971",
    "years_of_experience": 5,
    "spoken_languages": [
      "French","English","Arabic"
    ],
    "professional_biography": "I am a Dentist with 5 years of experience",
    "specialty_id": "6268ef32632cfdc52242206c",
    "certificate": { 
        "certificate_image": "certificate.jpg", 
        "is_verified": "true"
    },
    "clinic": {
      "name": "Super Dentist",
      "location": {
           "x": 100, 
           "y": 100, 
           "region_name": "Dental Land" 
        }
    }
}

### Get By query
GET http://localhost:5000/doctor?years_of_experience=5&clinic.location.x=100


### Aggregation with basic user
GET http://localhost:5000/doctor/aggregate/basic_user

### Get specialty by name
GET http://localhost:5000/specialty?specialty_name
