### Testing REST APIs

### Get all

GET http://localhost:5000/basicUser

### Get by id

GET http://localhost:5000/basicUser/62654f2597fb64052d7af5de

### Create one

POST http://localhost:5000/basicUser
Content-Type: application/json

{
    "first_name": "Harry",
    "last_name": "Lary",
    "gender": "male",
    "date_of_birth": "2011-09-01T00:00:00.000Z",
    "phone_number": "8144 2456",
    "profile_picture": "https://res.cloudinary.com/dvgjsemgk/image/upload/v1652365586/doctors_images/1000_F_143819453_Eai3IbcXhhGGoCWY5lso1ijI9nH387yC_ht33tg.jpg"
}

### Update one
PATCH http://localhost:5000/basicUser/62654f2597fb64052d7af5de
Content-Type: application/json

{
    "first_name":"New Name"
}

### Delete one
DELETE http://localhost:5000/basicUser/62654f2597fb64052d7af5de

### Get Specialty by name
GET http://localhost:5000/basicUser?first_name=Marwan&phone_number=71223456

### Get All doctors
GET http://localhost:5000/doctor

### Create doctor
POST http://localhost:5000/doctor
Content-Type: application/json

{
    "basic_user_id": "627d1cb75a9e2e04f27519e8",
    "years_of_experience": 5,
    "spoken_languages": [
      "French","English","Arabic"
    ],
    "professional_biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "specialty_id": "6268ef32632cfdc52242206c",
    "certificate": { 
        "certificate_image": "certificate.jpg", 
        "is_verified": "true"
    },
    "clinic": {
      "name": "Super Dentist",
      "location": {
           "x": 100, 
           "y": 100, 
           "region_name": "Dental Land" 
        }
    }
}


### For the patient


### Get all 

GET http://localhost:5000/patient

### Get by id

GET http://localhost:5000/patient?basic_user_id=6256cae0f6d570985782ae3f

### Create one

POST http://localhost:5000/patient
Content-Type: application/json

{
 "basic_user_id":"6256cae0f6d570985782ae3f",
 "total_spent":0
}

### Update one
PATCH http://localhost:5000/basicUser/62654f2597fb64052d7af5de
Content-Type: application/json

{
    "first_name":"New Name"
}

### Delete one
DELETE http://localhost:5000/basicUser/62654f2597fb64052d7af5de

### Get Specialty by name
GET http://localhost:5000/basicUser?first_name=Marwan&phone_number=71223456




### For the account


### Get all

GET http://localhost:5000/account

### Get by id

GET http://localhost:5000/account/62718057b50c3c61ec5774b4

### Create one

POST http://localhost:5000/account
Content-Type: application/json

{
    "email": "cas@gmail.com",
    "username": "gerg",
    "password": "carlos1234",
    "balance": "0",
    "is_activated": false
}

### Update one
PATCH http://localhost:5000/account/62718057b50c3c61ec5774b4
Content-Type: application/json

{
    "email":"New email"
}

### Delete one
DELETE http://localhost:5000/account/62718057b50c3c61ec5774b4

### Get Specialty by name
GET http://localhost:5000/account?username=ger

### Get By query
GET http://localhost:5000/doctor?years_of_experience=5&clinic.location.x=100


### Aggregation with basic user
GET http://localhost:5000/doctor/aggregate/basic_user?doctor_name=Ali&specialty_id=6268ef32632cfdc52242206c

### Get specialty by name
GET http://localhost:5000/specialty?specialty_name=den

### Login
POST http://localhost:5000/account/login
Content-Type: application/json

{
    "email" : "carlos@gmail.com",
    "password":"carlos1234"
}

### 
GET http://localhost:5000/account/is/logged_in